### PR TITLE
Fix debug images for shells

### PR DESCRIPTION
**Pull request by rxnm**
# Overview
*Provide a brief overview of the purpose of this pull request*

# Details
*Provide details on the change you are making, why they are necessary, and any information that will help with understanding.*

# UI Changes / Functionality
*Include a before and after screenshot/recording if applicable. Short recordings showing that your changes work are helpful, but optional.*

# Testing Steps
*Provide a list of repro steps on how to test that your changes are valid.*

- [ ] Did you test the changes you made?
- [ ] Did you test core functionality of the script to ensure your changes do not regress other areas?
- [ ] Did you test your changes in multiplayer to ensure it works correctly on all clients?

### CODE REVIEW

**Comment by xFutte** [comment]
@rxnm, please also add the src file with the updated links. Otherwise, all the links will revert to the old ones, when this is recompiled locally.

**Review by xFutte — CHANGES_REQUESTED** [review]
See comment.

**Comment by rxnm** [comment]
> @rxnm, please also add the src file with the updated links. Otherwise, all the links will revert to the old ones, when this is recompiled locally.

Hey mate, not quite sure how to do this, mind explaining more? thanks.

**Comment by complexza** [comment]
@rxnm You can check if your git is ignoring it, If it is, then you need to remove it then you can push the source files, and by source files, it's the svelte files you edited.

**Comment by rxnm** [comment]
Should be fine now, sorry for the mistake, quite new to svelte.

**Review by xFutte — APPROVED** [review]
LGTM!

**Pull request merged**
