### PR TITLE
hotfix: trim-error

### PR DESCRIPTION
**Pull request by RanDXDev**
# Overview
Fix trim issue when having 0 properties and pressing on the add property button

# Details
Fixing trim issue on ps realtor, sometimes the string is undefined, but if you force to call trim function it will throw error and messed up the UI, so adding a optional chaining operator (`?`) prevent it to throw error 

# UI Changes / Functionality
Before fix:
https://streamable.com/30jzx3

After fix:
https://streamable.com/1q55yv

# Testing Steps
*Provide a list of repro steps on how to test that your changes are valid.*

- [✅] Did you test the changes you made?
- [✅ ] Did you test core functionality of the script to ensure your changes do not regress other areas?
- [❌] Did you test your changes in multiplayer to ensure it works correctly on all clients? (Don't have friend and my pc too potato😔)

### CODE REVIEW

**Comment by RanDXDev** [comment]
Wait writing more details, accidentally pressed the create pr

**Comment by LeSiiN** [comment]
Tested myself, working so far

**Comment by Martinator9001** [comment]
Worked for me as well.

**Comment by Martinator9001** [comment]
Also tried it out with my realtor a while ago, so you can mark off the 3rd one

**Comment by Martinator9001** [comment]
Another happy camper: https://discord.com/channels/897744257237000222/900180032935325707/1145810611301785661

**Comment by MonkeyWhisper** [comment]
Tested myself on a fresh copy was able to duplicate the issue and this fixed it

**Pull request merged**
