### PR TITLE
Added bl-realtor PR's back in / Changed some text

### PR DESCRIPTION
**Pull request by LeSiiN**
- added https://github.com/Byte-Labs-Project/bl-realtor/pull/8
- added https://github.com/Byte-Labs-Project/bl-realtor/pull/6
- changed **`Write a short and sweet description about yourself...`** to **`Write a short and sweet description about the property...`**
- changed **`Some instructions lorem lpsum is simply dummy text of printing`** to something that ffits better, for example for Live Description **`Change the settings after the creation!`**

### CODE REVIEW

**Comment by Martinator9001** [comment]
Currently without this PR every time a realtor leaves or joins your realtor's job becomes unemployed.

**Comment by LeSiiN** [comment]
> 

what ? without the PR ? i got the same WITH the PR

**Comment by Martinator9001** [comment]
Well technically I didn't do the PR 1:1, but I removed the setting the job from the ps-realtor script and added the job in jobs.lua in qb-core.

**Comment by Martinator9001** [comment]
> > Currently without this PR every time a realtor leaves or joins your realtor's job becomes unemployed.
> 
> what ? without the PR ? i got the same WITH the PR

Well technically I didn't do the PR 1:1, but I removed the setting the job from the ps-realtor script and added the job in jobs.lua in qb-core.

**Pull request merged**
